# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lot8OfVhyecXugMmUoxHJFD5gRG73e1I
"""



import gym
import pygame
from pygame import gfxdraw

env_id = "CartPole-v1"
# Create the env
env = gym.make(env_id)

state = env.reset()

for t in range(100):
    env.render() # A window pops up rendering CartPole
    print(state)

    action = env.action_space.sample() # A random action
    state, reward, done, info = env.step(action)

    if done:
        print('Finished')
        break

env.close()